#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[奇蛋物语/ワンダーエッグ・プライオリティ/WONDER EGG PRIORITY][01-13][BDRip][1080p][简繁日外挂][招募翻译]"
group_name="[喵萌奶茶屋]"
poster="https://s2.loli.net/2022/11/06/6WSjknu5PUrL2w8.jpg"
about="https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-MIR-Subs/tree/master/WEP"
# Use ''' to avoid escape
filename_regex=""
resolution_regex=""
has_subtitle=true
is_finished=true

[[intro_template]]
site="nyaa"
name="nekomoekissaten"
cookie="session=xxx"
user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
content="Publish_BDRip_Nyaa.md"
