#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[機動戰士鋼彈 水星的魔女/Mobile Suit Gundam THE WITCH FROM MERCURY][序幕+<ep>][BDRip][<res>p][繁日雙語][招募翻譯]"
group_name="[喵萌奶茶屋]"
poster="https://nekomoe.pages.dev/images/2022-10/w1000/g-witch_1000.png"
about="https://github.com/Nekomoekissaten-SUB"
# Use ''' to avoid escape
# filename_regex='''\]\[(?<ep>\d{2})\]\['''
filename_regex="\\]\\[(?<ep>\\d{2}\\-\\d{2})\\]\\["
resolution_regex='''\]\[(?<res>\d{3}|\d{4})p\]\['''
tags=["Anime", "TV", "Collection"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"

# [[intro_template]]
# site="bangumi"
# name="喵萌奶茶屋"

[[intro_template]]
site="acgnx_asia"
name="174"