#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[杜鹃的婚约 / Kakkou no Iinazuke / A Couple of Cuckoos][01-24+Mini_01-22][BDRip][1080p][简繁外挂][招募翻译]"
group_name="[喵萌奶茶屋]"
poster="https://nekomoe.pages.dev/images/2022-04/w1000/kakkou_1000.jpg"
about="https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/tree/master/Cuckoos"
# Use ''' to avoid escape
filename_regex=""
resolution_regex=""
tags=["Anime", "Collection"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"
