#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[工作細胞BLACK / Hataraku Saibou Black][<ep>][BDRip][<res>p][繁體][招募翻譯]"
group_name="[喵萌奶茶屋]"
poster="https://nekomoe.pages.dev/images/2021-01/w1000/hataraku-saibou_black_1000.jpg"
about="https://github.com/Nekomoekissaten-SUB"
# Use ''' to avoid escape
filename_regex="\\]\\[(?<ep>\\d{2}\\-\\d{2})\\]\\["
resolution_regex='''\]\[(?<res>\d{3}|\d{4})p\]\['''
has_subtitle=true
is_finished=true

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"

[[intro_template]]
site="bangumi"
name="喵萌奶茶屋"