#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌Production】★07月新番★[闪耀路标/SHINE POST][<ep>][<res>p][简日双语][招募翻译]"
group_name="[喵萌奶茶屋]"
poster="https://s2.loli.net/2022/07/14/ABzepvRE9aSGlIy.jpg"
about="https://github.com/Nekomoekissaten-SUB"
# Use ''' to avoid escape
filename_regex="POST\\]\\[(?<ep>\\d{2}\\-\\d{2})\\]\\["
resolution_regex='''\]\[(?<res>\d{3}|\d{4})p\]\['''
has_subtitle=true
is_finished=true

[[intro_template]]
site="nyaa"
name="nekomoekissaten"
cookie="session=xxx"
user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
content="Publish_Chs_Nyaa.md"
