#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】★04月新番★[与山田谈一场Lv999的恋爱 / Yamada-kun to Lv999 no Koi wo Suru][<ep>][<res>p][简日双语][招募翻译]"
group_name="[喵萌奶茶屋]"
poster="https://s2.loli.net/2023/04/05/XI9MNiUVx1gvzCy.jpg"
about="https://github.com/Nekomoekissaten-SUB"
# Use ''' to avoid escape
# filename_regex='''\]\[(?<ep>\d{2})\]\['''
filename_regex="\\]\\[(?<ep>\\d{2}\\-\\d{2})\\]\\["
resolution_regex='''\]\[(?<res>\d{3}|\d{4})p\]\['''
tags=["Anime", "TV", "Collection"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"

# [[intro_template]]
# site="bangumi"
# name="喵萌奶茶屋"

# [[intro_template]]
# site="acgnx_asia"
# name="174"

# [[intro_template]]
# site="acgnx_global"
# name="212"