#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[RPG不动产/RPG Fudousan][01-12][BDRip][1080p][简繁日外挂][招募翻译]"
group_name="[喵萌奶茶屋]"
poster="https://nekomoe.pages.dev/images/2022-04/rpg-rs.jpg"
about="https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-MIR-Subs/tree/master/RPG_Fudousan"
# Use ''' to avoid escape
filename_regex=""
resolution_regex=""
has_subtitle=true
is_finished=true

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"
