#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[莉可丽丝 / Lycoris Recoil][01-13][BDRip][1080p][简繁外挂][招募翻译]"
group_name="[喵萌奶茶屋]"
poster="https://nekomoe.pages.dev/images/2022-07/w1000/lycoris-recoil_1000.jpg"
about="https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/tree/master/Lycoris_Recoil"
# Use ''' to avoid escape
filename_regex=""
resolution_regex=""
tags=["Anime", "Collection"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"
