#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[夢想成為魔法少女 / 憧憬成為魔法少女 / Mahou Shoujo ni Akogarete][<ep>][BDRip][<res>p][繁日雙語][招募翻譯時軸]"
group_name="[喵萌奶茶屋]"
poster="https://s2.loli.net/2024/01/06/H3fr8sGEJZgj2xv.webp"
about="https://github.com/Nekomoekissaten-SUB"
# Use ''' to avoid escape
filename_regex="\\]\\[(?<ep>\\d{2}\\-\\d{2})\\]\\["
# filename_regex='''\]\[(?<ep>\d{2})\]\['''
resolution_regex='''\]\[(?<res>\d{3}|\d{4})p\]\['''
tags=["Anime", "TV", "Batch"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"

# [[intro_template]]
# site="bangumi"
# name="喵萌奶茶屋"

# [[intro_template]]
# site="acgnx_asia"
# name="174"

# [[intro_template]]
# site="acgnx_global"
# name="212"