#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[戀愛要在征服世界後 / Koi wa Sekai Seifuku no Ato de][<ep>][BDRip][<res>p][繁日雙語][招募翻譯]"
group_name="[喵萌奶茶屋]"
poster="https://p.sda1.dev/5/26fd9d35c0880e36a915421860ef004f/b1c9b266-e536-4f79-8b80-3f34912d5526_1000.jpg"
about="https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/tree/master/Koiseka"
# Use ''' to avoid escape
filename_regex="\\]\\[(?<ep>\\d{2}\\-\\d{2})\\]\\["
resolution_regex='''\]\[(?<res>\d{3}|\d{4})p\]\['''
tags=["Anime", "Collection"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"
