#Make sure you have both <ep> in display_name and valid filename_regex. Other wise OKP will not match your ep number.
display_name="【喵萌奶茶屋】[恋爱要在征服世界后 / Koi wa Sekai Seifuku no Ato de][01-12][BDRip][1080p][简繁日外挂][招募翻译]"
group_name="[喵萌奶茶屋]"
poster="https://p.sda1.dev/5/26fd9d35c0880e36a915421860ef004f/b1c9b266-e536-4f79-8b80-3f34912d5526_1000.jpg"
about="https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-MIR-Subs/tree/master/Koiseka"
# Use ''' to avoid escape
filename_regex=""
resolution_regex=""
tags=["Anime", "Collection"]

[[intro_template]]
site="nyaa"
name="nekomoekissaten"

[[intro_template]]
site="dmhy"
name="喵萌奶茶屋"

[[intro_template]]
site="acgrip"
name="喵萌奶茶屋"
